wordpress_sites:
  ianhilt.com:
    site_hosts:
      - canonical: ianhilt.com
        redirects:
          - www.ianhilt.com
    local_path: ../site
    repo: git@github.com:ihilt/ianhilt.com.git
    repo_subtree_path: site
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
